name: Code Quality

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
   
jobs:
  test:
    runs-on: ubuntu-latest
    name: Lint Scan
    steps:
      - uses: actions/checkout@v2
      - name: Lint Scan
        uses: overtrue/phplint@8.1
        with:
          path: .
          options: --json=result.json
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Lint Report
           path: ${{github.workspace}}/result.json
  
  Code_Style:
    runs-on: ubuntu-latest
    name: Code Style Scan
    steps:        
       - uses: actions/checkout@v2
       - name: Code Style
         uses: creyD/prettier_action@v4.2
 
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run PHP CS Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=.php_cs.dist --allow-risky=yes

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v2.3.0
        with:
          commit_message: Fix styling
          branch: ${{ github.head_ref }}
