name: Code Quality

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
   
jobs:
  test:
    runs-on: ubuntu-latest
    name: Lint Scan
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Lint Scan
        uses: overtrue/phplint@8.1
        with:
          path: .
          options: --exclude=*.log --json=result.json
      - name: Code Style
        uses: creyD/prettier_action@v4.2
      - name: Upload Test results
        uses: actions/upload-artifact@master
        with:
           name: Lint Report
           path: ${{github.workspace}}/result.json
